/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const T__1 = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'price' : IDL.Float64,
});
export const T = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const BusinessInfo = IDL.Record({
  'name' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'addProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [T__1], []),
  'addProductCategory' : IDL.Func([IDL.Text, IDL.Text], [T], []),
  'getAllProductCategories' : IDL.Func([], [IDL.Vec(T)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
  'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [T__1], ['query']),
  'getProductCategory' : IDL.Func([IDL.Nat], [T], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const T__1 = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'price' : IDL.Float64,
  });
  const T = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
  });
  const BusinessInfo = IDL.Record({
    'name' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'addProduct' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [T__1], []),
    'addProductCategory' : IDL.Func([IDL.Text, IDL.Text], [T], []),
    'getAllProductCategories' : IDL.Func([], [IDL.Vec(T)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(T__1)], ['query']),
    'getBusinessInfo' : IDL.Func([], [BusinessInfo], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [T__1], ['query']),
    'getProductCategory' : IDL.Func([IDL.Nat], [T], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };